Style/Documentation:
  Enabled: false

Style/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
