# Vim mode
set -o vi

# Source machine-specific config
if [[ -f "$HOME/.$HOSTNAME.bash" ]]; then
  source "$HOME/.$HOSTNAME.bash"
fi

# Paths
# For golang
GOPATH=$HOME/go
PATH=$HOME/go/bin:$PATH

# For rustup
PATH=$HOME/.cargo/bin:$PATH

# Always use user-defined programs before system-defined ones
PATH=$HOME/bin:$PATH

# For rbenv
PATH=$HOME/.rbenv/bin:$PATH

export PATH

# Prompt
export PS1="[\u@\h \W]\$ "

# Set editor and less flags
export EDITOR=vim
export LESS='-F -g -i -M -S -w -X -z-4'

# Alias neovim if we have it
if hash "nvim"; then
  alias vim="nvim"
  alias vi="nvim"
else
  alias vi="vim"
fi

# System specific ls aliases
if [[ "$OSTYPE" == darwin* ]]; then
  alias ls="ls -lhFG"
  alias la="ls -alhGF"
else
  alias ls="ls -lhF --color=auto"
  alias la="ls -alhF --color=auto"
fi

# key bindings
stty werase undef
bind '\C-f:forward-search-history'
bind '\C-w:backward-kill-word'
