#!/bin/bash

# Vim mode
set -o vi

# function for going back to root of git repo
function git_root {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    cd $(git rev-parse --show-toplevel)
  else
    >&2 echo "Error, not inside a git repository"
    false
  fi
}

alias cdgr="git_root"

# Alias neovim if we have it
if hash "nvim"; then
  alias vim="nvim"
  alias vi="nvim"
else
  alias vi="vim"
fi

# Mac aliases for ls
if [[ "$OSTYPE" == darwin* ]]; then
  alias ls="ls -lhFG"
  alias la="ls -alhGF"
else
  alias ls="ls -lhF --color=auto"
  alias la="ls -alhF --color=auto"
fi

alias quit="exit"

# key bindings
stty werase undef
bind '\C-f:forward-search-history'
bind '\C-w:backward-kill-word'

# Prompt
export PS1="[\u@\h \W]\$ "
