#!/bin/bash
# Make sure to read bashrc every time we log in
if [ -f ~/.bashrc ]
  then
    source ~/.bashrc
fi

export editor=vim
export LESS='-F -g -i -M -R -S -w -X -z-4'

if [[ -n $(command -v rbenv) ]]; then
  eval "$(rbenv init -)"
fi
